services:
  db:
    image: postgres:16
    container_name: cursos_tamayoshi
    environment:
      POSTGRES_DB: gestao_cursos
      POSTGRES_USER: cursos
      POSTGRES_PASSWORD: 123123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
